/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.crud_jdbc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author pedro
 */
public class Detalles_Pedidos extends javax.swing.JDialog {

    /**
     * Creates new form Detalles_Pedidos
     */
    public Detalles_Pedidos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 450));
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MOSTRAR DETALLES DE PEDIDOS");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(3, 0));

        jPanel3.setLayout(new java.awt.GridLayout(0, 2));

        jPanel6.setLayout(new java.awt.GridLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ID PEDIDO");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 40, 1, 1));
        jPanel6.add(jLabel2);

        jPanel3.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 60, 40, 60));
        jPanel7.setLayout(new java.awt.GridLayout());
        jPanel7.add(jTextField1);

        jPanel3.add(jPanel7);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane1);

        jPanel2.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 100, 30, 100));
        jPanel5.setLayout(new java.awt.GridLayout());

        jButton1.setText("Mostrar detalles");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        jPanel2.add(jPanel5);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Boton para mostrar los detalles
        String driver = "com.mysql.cj.jdbc.Driver";
        String URL = "jdbc:mysql://localhost:3306/tienda_db";
        String usuario = "root";
        String password = "pedro";
        
        int totalPedido = 0;
        
        int id_pedido = Integer.parseInt(jTextField1.getText());
        
        //Cargar el driver de la base de datos(puede que sea necesario cargar .jar)
        try{
        Class.forName(driver);
        
        //Establecer conexión con mysql
        Connection dbConnection = DriverManager.getConnection(URL, usuario, password);
        
        //Consultas
        String consulta1 = "SELECT cliente.nombre AS nombreCliente, cliente.ciudad AS ciudadCliente, pedido.fecha AS fechaPedido, " +
                   "producto.nombre AS nombreProducto, pedido_producto.cantidad AS cantidad, producto.precio AS precio, " +
                   "(pedido_producto.cantidad * producto.precio) AS subtotal " +
                   "FROM pedido " +
                   "INNER JOIN cliente ON pedido.id_cliente = cliente.id_cliente " +
                   "INNER JOIN pedido_producto ON pedido.id_pedido = pedido_producto.id_pedido " +
                   "INNER JOIN producto ON pedido_producto.id_producto = producto.id_producto " +
                   "WHERE pedido.id_pedido = " + id_pedido;

        
        //Crear una declaracion para ejecutar la consulta
        Statement statement = dbConnection.createStatement();
        
        //Ejecutar la consulta y obtener resultados
        ResultSet rs = statement.executeQuery(consulta1);
        
        //Recorrer a través de los resultados
        while(rs.next()){
            String nombreCliente = rs.getString("nombreCliente");
            String fecha = rs.getString("fechaPedido");
            String ciudadCliente = rs.getString("ciudadCliente");
            String nombreProducto = rs.getString("nombreProducto");
            int cantidadpp = rs.getInt("cantidad");
            int precioProducto = rs.getInt("precio");
            int subtotal = rs.getInt("subtotal");

            totalPedido += subtotal;
           
           jTextArea1.append(" Nombre del cliente: " + nombreCliente + "\n" + "\n" +
                              " Fecha: " + fecha + "\n" + "\n" +
                              " Ciudad del cliente: " + ciudadCliente + "\n" + "\n" +
                              " Nombre del producto: " + nombreProducto + "\n" + "\n" +
                              " Cantidad: " + cantidadpp + "\n" + "\n" +
                              " Precio del producto: " + precioProducto + "\n" + "\n" +
                              " SUBTOTAL: " + subtotal + "\n" +"\n" +
                   "==============================" + "\n" + " TOTAL PEDIDO: " + totalPedido + "\n"); 
        }
         
        }catch (ClassNotFoundException e){
            System.out.println("Error");
        }catch (SQLException e){
            System.out.println("Error");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detalles_Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detalles_Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detalles_Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detalles_Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Detalles_Pedidos dialog = new Detalles_Pedidos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
