/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.crud_jdbc;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author pedro
 */
public class Gestion_De_Pedidos extends javax.swing.JFrame {

    /**
     * Creates new form Gestion_De_Pedidos
     */
    public Gestion_De_Pedidos() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
            FlatLaf.updateUI();
        } catch (Exception e) {
            System.out.println("Error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 700));
        getContentPane().setLayout(new java.awt.GridLayout(6, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 1, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoGestion.png"))); // NOI18N
        jLabel1.setText("GESTIÓN DE PEDIDOS");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 100, 20, 100));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoCliente.png"))); // NOI18N
        jButton1.setText("Registrar nuevo cliente");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new java.awt.GridBagConstraints());

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojo.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(jButton6, gridBagConstraints);

        getContentPane().add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 100, 20, 100));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoProducto.png"))); // NOI18N
        jButton2.setText("Registrar nuevo producto");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new java.awt.GridBagConstraints());

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojo.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 3.0;
        jPanel3.add(jButton7, gridBagConstraints);

        getContentPane().add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 100, 20, 100));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoPedido.png"))); // NOI18N
        jButton3.setText("Registrar nuevo pedido");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new java.awt.GridBagConstraints());

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojo.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(jButton8, gridBagConstraints);

        getContentPane().add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 100, 20, 100));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoConsultar.png"))); // NOI18N
        jButton4.setText("Consultar pedido");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4);

        getContentPane().add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 100, 20, 100));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoEliminar.png"))); // NOI18N
        jButton5.setText("Eliminar producto de un pedido");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5);

        getContentPane().add(jPanel6);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Boton para registrar nuevo cliente
        Registrar_Cliente registroCliente = new Registrar_Cliente(this, true);
        registroCliente.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Boton para registrar nuevo producto
        Registrar_Producto registroProducto = new Registrar_Producto(this, true);
        registroProducto.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //Boton para eliminar producto de un pedido
        Eliminar_ProductoDePedido eliminarProductoPedido = new Eliminar_ProductoDePedido(this, true);
        eliminarProductoPedido.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Boton para mostrar todos los detalles de los pedidos de los clientes
        Detalles_Pedidos mostrarDetalles = new Detalles_Pedidos(this, true);
        mostrarDetalles.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Boton para registrar un nuevo pedido
        Registrar_Pedido registrarPedido = new Registrar_Pedido(this, true);
        registrarPedido.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //Boton para ver los clientes
        
        String driver = "com.mysql.cj.jdbc.Driver";
        String URL = "jdbc:mysql://localhost:3306/tienda_db";
        String usuario = "root";
        String password = "pedro";
        
        //Cargar el driver de la base de datos(puede que sea necesario cargar .jar)
        try{
        Class.forName(driver);
        
        //Establecer conexión con mysql
        Connection dbConnection = DriverManager.getConnection(URL, usuario, password);
        
        //Consultas
        String consulta1 = "SELECT * FROM cliente";
                         
        //Crear una declaracion para ejecutar la consulta
        Statement statement = dbConnection.createStatement();
        
        //Ejecutar la consulta y obtener resultados
        ResultSet rs = statement.executeQuery(consulta1);
        
        //Recorrer a través de los resultados
        
        StringBuilder resumen = new StringBuilder();
        
        while(rs.next()){
           int idCliente = rs.getInt("id_cliente");
           String nombreCliente = rs.getString("nombre");
           int edad = rs.getInt("edad");
           String ciudadCliente = rs.getString("ciudad");
           
            resumen.append("ID: ").append(idCliente)
           .append(" -Nombre: ").append(nombreCliente)
           .append(" -Edad: ").append(edad)
           .append(" -Ciudad: ").append(ciudadCliente)
           .append("\n");
           
        }
        
        ClaseAuxiliar.resumenClientes = resumen.toString();
        
        VerClientes verclientes = new VerClientes(this, true);
        verclientes.setVisible(true);

         
        }catch (ClassNotFoundException e){
            System.out.println("Error");
        }catch (SQLException e){
            System.out.println("Error");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //Boton para ver todos los productos
        
        String driver = "com.mysql.cj.jdbc.Driver";
        String URL = "jdbc:mysql://localhost:3306/tienda_db";
        String usuario = "root";
        String password = "pedro";
        
        //Cargar el driver de la base de datos(puede que sea necesario cargar .jar)
        try{
        Class.forName(driver);
        
        //Establecer conexión con mysql
        Connection dbConnection = DriverManager.getConnection(URL, usuario, password);
        
        //Consultas
        String consulta1 = "SELECT * FROM producto";
                         
        //Crear una declaracion para ejecutar la consulta
        Statement statement = dbConnection.createStatement();
        
        //Ejecutar la consulta y obtener resultados
        ResultSet rs = statement.executeQuery(consulta1);
        
        //Recorrer a través de los resultados
        
        StringBuilder resumen = new StringBuilder();
        
        while(rs.next()){
           int idProducto = rs.getInt("id_producto");
           int precio = rs.getInt("precio");
           String nombreProducto = rs.getString("nombre");
           int stock = rs.getInt("stock");
           
            resumen.append("ID: ").append(idProducto)
           .append(" -Nombre: ").append(nombreProducto)
           .append(" -Precio: ").append(precio)
           .append(" -Stock: ").append(stock)
           .append("\n");
           
        }
        
        
        ClaseAuxiliar.resumenProductos = resumen.toString();
        
        VerProductos verproductos = new VerProductos(this, true);
        verproductos.setVisible(true);

         
        }catch (ClassNotFoundException e){
            System.out.println("Error");
        }catch (SQLException e){
            System.out.println("Error");
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //Boton para ver todos los pedidos
        
        String driver = "com.mysql.cj.jdbc.Driver";
        String URL = "jdbc:mysql://localhost:3306/tienda_db";
        String usuario = "root";
        String password = "pedro";
        
        //Cargar el driver de la base de datos(puede que sea necesario cargar .jar)
        try{
        Class.forName(driver);
        
        //Establecer conexión con mysql
        Connection dbConnection = DriverManager.getConnection(URL, usuario, password);
        
        //Consultas
        String consulta1 = "SELECT * FROM pedido";
                         
        //Crear una declaracion para ejecutar la consulta
        Statement statement = dbConnection.createStatement();
        
        //Ejecutar la consulta y obtener resultados
        ResultSet rs = statement.executeQuery(consulta1);
        
        //Recorrer a través de los resultados
        
        StringBuilder resumen = new StringBuilder();
        
        while(rs.next()){
           int idPedido = rs.getInt("id_pedido");
           String fecha = rs.getString("fecha");
           int idCliente = rs.getInt("id_cliente");
           
            resumen.append("ID_PEDIDO: ").append(idPedido)
           .append(" -ID_CLIENTE: ").append(idCliente)
           .append(" -Fecha: ").append(fecha)
           .append("\n");
           
        }
        
        ClaseAuxiliar.resumenPedidos = resumen.toString();
        
        VerPedidos verpedidos = new VerPedidos(this, true);
        verpedidos.setVisible(true);

         
        }catch (ClassNotFoundException e){
            System.out.println("Error");
        }catch (SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_De_Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_De_Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_De_Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_De_Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_De_Pedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
