/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.crud_jdbc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class Registrar_Pedido extends javax.swing.JDialog {

    /**
     * Creates new form Registrar_Pedido
     */
    public Registrar_Pedido(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    
        ArrayList<Integer> idProductos = new ArrayList<>();
        ArrayList<Integer> cantidadProductos = new ArrayList<>();
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRAR PEDIDO");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(3, 0));

        jPanel3.setLayout(new java.awt.GridLayout(1, 1));

        jPanel9.setLayout(new java.awt.GridLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ID CLIENTE");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 40, 1, 1));
        jPanel9.add(jLabel2);

        jPanel3.add(jPanel9);

        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 60, 40, 60));
        jPanel10.setLayout(new java.awt.GridLayout());
        jPanel10.add(jTextField1);

        jPanel3.add(jPanel10);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 3));

        jPanel6.setLayout(new java.awt.GridLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("ID PRODUCTO - CANTIDAD");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 40, 1, 1));
        jPanel6.add(jLabel3);

        jPanel4.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(60, 40, 60, 40));
        jPanel7.setLayout(new java.awt.GridLayout(1, 2, 10, 1));
        jPanel7.add(jTextField2);
        jPanel7.add(jTextField3);

        jPanel4.add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(60, 80, 60, 80));
        jPanel8.setLayout(new java.awt.GridLayout());

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1);

        jPanel4.add(jPanel8);

        jPanel2.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 200, 50, 200));
        jPanel5.setLayout(new java.awt.GridLayout());

        jButton2.setText("Registrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);

        jPanel2.add(jPanel5);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                           
    //Boton para guardar id y cantidad en un ArrayList
    int id_producto = Integer.parseInt(jTextField2.getText()); 
    idProductos.add(id_producto);

    int cantidad = Integer.parseInt(jTextField3.getText()); 
    cantidadProductos.add(cantidad);

    JOptionPane.showMessageDialog(null, "Producto agregado: ID=" + id_producto + ", Cantidad=" + cantidad);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Boton para hacer registro total
        String driver = "com.mysql.cj.jdbc.Driver";
        String URL = "jdbc:mysql://localhost:3306/tienda_db";
        String usuario = "root";
        String password = "pedro";  
    
    try {
        Class.forName(driver);
        Connection dbConnection = DriverManager.getConnection(URL, usuario, password);

        Statement statement = dbConnection.createStatement();

        // Insertar pedido
        int idCliente = Integer.parseInt(jTextField1.getText());
        String sqlInsertPedido = "INSERT INTO pedido (fecha, id_cliente) VALUES (CURDATE(), " + idCliente + ")";
        statement.executeUpdate(sqlInsertPedido, Statement.RETURN_GENERATED_KEYS);

        //Obtener id
        int idPedido = 0;
        var rs = statement.getGeneratedKeys();
        if (rs.next()) {
            idPedido = rs.getInt(1);
        }

        //Insertar y actualizar
        for (int i = 0; i < idProductos.size(); i++) {
            int idProducto = idProductos.get(i);
            int cantidad = cantidadProductos.get(i);
            int stock = 0;
            
            //Recoger stock

            Statement st1 = dbConnection.createStatement();
            ResultSet rs2 = st1.executeQuery("SELECT stock FROM producto WHERE id_producto = " + idProducto);
            while (rs2.next()) {
                stock = rs2.getInt(("stock"));
            }
            
            // Insertar en pedido_producto
            String sqlInsertProducto = "INSERT INTO pedido_producto (id_pedido, id_producto, cantidad) " +
                                       "VALUES (" + idPedido + ", " + idProducto + ", " + cantidad + ")";
            statement.executeUpdate(sqlInsertProducto);

            // Actualizar stock
            
            int nuevoStock = stock - cantidad;
            String sqlActualizarStock = "UPDATE producto SET stock = " + nuevoStock +
                                        " WHERE id_producto = " + idProducto;
            statement.executeUpdate(sqlActualizarStock);
        }

        JOptionPane.showMessageDialog(null, "Pedido registrado con éxito. ID: " + idPedido);

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al registrar el pedido");
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Registrar_Pedido dialog = new Registrar_Pedido(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
